const express = require('express');
const stripe = require('stripe')('sk_test_51PtX5uLbeudqBLeNEAc5erBrRhOADLqzmk0AeUYntUFjcXhhuwtszfstPJl9yr44yFbeYsNTcwJP1JbxseuHRgzG00hGNa0eJM');
const bodyParser = require('body-parser');
const cors = require('cors');

// Convert json file structure
let fs = require('fs')
let Products = [
  {
    "id": 1,
    "arabic_name": "حليب جهينة",
    "english_name": "Juhayna Milk",
    "amount": 5,
    "price": 50,
    "catId": "5",
    "image_url": "https://3ard.com/cdn/shop/products/Untitled-4_0002s_0003_juhayna-juice_0000s_0033_jucies-114copy_0c74d542-0935-412c-ae6d-1d2b3ab60214_540x.jpg?v=1654984273",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 2,
    "arabic_name": "زبادي المراعي",
    "english_name": "Almarai Yogurt",
    "amount": 5,
    "price": 70,
    "catId": "5",
    "image_url": "https://lh6.googleusercontent.com/proxy/bUKIJiucH2wWGACIy-JJKZbXTBC8S181ZbDiseOHSs_kGE15j68MJQ3OSDaEAPnewFiwekvGx6C7nqgle76g1ke-uAHl4NDGR9XOXlYfe970MscETHKnw3BJnWoqbgnerR0",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 3,
    "arabic_name": "جبنة دومتي",
    "english_name": "Domty Cheese",
    "amount": 5,
    "price": 76,
    "catId": "5",
    "image_url": "https://images.deliveryhero.io/image/darkstores-eg/EGY_6223000758847.JPG",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 4,
    "arabic_name": "زبدة لورباك",
    "english_name": "Lurpak Butter",
    "amount": 5,
    "price": 76,
    "catId": "5",
    "image_url": "https://www.shutterstock.com/image-photo/london-uk-01222023-lurkak-butter-260nw-2253016637.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 5,
    "arabic_name": "جبنة فيتا",
    "english_name": "Feta Cheese",
    "amount": 5,
    "price": 76,
    "catId": "5",
    "image_url": "https://www.cheese.com/media/img/cheese/feta_cheese_on_cutting_board.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 6,
    "arabic_name": "حليب المراعي",
    "english_name": "Almarai Milk",
    "amount": 5,
    "price": 66,
    "catId": "5",
    "image_url": "https://d2wdttfod93r0n.cloudfront.net/Gallery/Almarai_UHT_Milk_1L_Rich-&-Creamy_3D_EN1242024113827AM.png",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 7,
    "arabic_name": "جبنة كيري",
    "english_name": "Kiri Cheese",
    "amount": 5,
    "price": 66,
    "catId": "5",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8RZznB_gnbbDU8Hhd4aH9cq0Cp5F8OwOKzQ&s",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 8,
    "arabic_name": "قشطة بوك",
    "english_name": "Puck Cream",
    "amount": 5,
    "price": 66,
    "catId": "5",
    "image_url": "https://m.media-amazon.com/images/I/91NsfI8EDCL._SL1500_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 9,
    "arabic_name": "تفاح",
    "english_name": "Apple",
    "amount": 5,
    "price": 500,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/61N6GttGioL._AC_UF894,1000_QL80_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 10,
    "arabic_name": "موز",
    "english_name": "Banana",
    "amount": 20,
    "price": 2,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/61RiB7mcfKL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 11,
    "arabic_name": "برتقال",
    "english_name": "orange",
    "amount": 1500,
    "price": 600,
    "catId": "4",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIlQ3sPNm-faMvvR-v_sKI62Aed4Uv1gEXFg&s",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 12,
    "arabic_name": "فراوله",
    "english_name": "Strawberry",
    "amount": 6,
    "price": 800,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/71sZf062IYS.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 13,
    "arabic_name": "عنب",
    "english_name": "Grapes",
    "amount": 6,
    "price": 900,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/81zvb9QzyPL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },

  {
    "id": 13,
    "arabic_name": "طماطم",
    "english_name": "Tomato",
    "amount": 1,
    "price": 5,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/512bN4AY0DL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 14,
    "arabic_name": "خيار",
    "english_name": "Cucumber",
    "amount": 1,
    "price": 3,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/41jShqGvYgL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 15,
    "arabic_name": "بطاطس",
    "english_name": "Potato",
    "amount": 1,
    "price": 4,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/612jH7iekTL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 16,
    "arabic_name": "بصل",
    "english_name": "Onion",
    "amount": 1,
    "price": 6,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/71GUFttn0jL._AC_UF1000,1000_QL80_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 17,
    "arabic_name": "جزر",
    "english_name": "Carrot",
    "amount": 1,
    "price": 7,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/71S6oQqVa5L.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 18,
    "arabic_name": "فلفل رومي",
    "english_name": "Bell Pepper",
    "amount": 1,
    "price": 8,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/41tZQUU+lML._SY300_SX300_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 19,
    "arabic_name": "كوسة",
    "english_name": "Zucchini",
    "amount": 1,
    "price": 5,
    "catId": "4",
    "image_url": "https://images-na.ssl-images-amazon.com/images/I/91MOgG7ihYL._AC_UL600_SR600,600_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 20,
    "arabic_name": "باذنجان",
    "english_name": "Eggplant",
    "amount": 1,
    "price": 9,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/51EWzWplV1L._AC_UF894,1000_QL80_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 21,
    "arabic_name": "قرنبيط",
    "english_name": "Cauliflower",
    "amount": 1,
    "price": 10,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/81Rmb+RaBHL._AC_UF1000,1000_QL80_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 22,
    "arabic_name": "كرفس",
    "english_name": "Celery",
    "amount": 1,
    "price": 6,
    "catId": "4",
    "image_url": "https://m.media-amazon.com/images/I/41-boo6FQ9L._AC_UF1000,1000_QL80_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": ""
  },
  {
    "id": 23,
    "arabic_name": "زيت عباد الشمس",
    "english_name": "Sunflower Oil",
    "amount": 5,
    "price": 46,
    "catId": "6",
    "image_url": "https://www.eatingwell.com/thmb/BatmJma8il7UHs58eyBSdGTg_sc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/sunflower-oil-caebdc08b58c4afe8456a40e5e8dd030.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "35%"
  },
  {
    "id": 24,
    "arabic_name": "زيت زيتون",
    "english_name": "Olive Oil",
    "amount": 44,
    "price": 46,
    "catId": "6",
    "image_url": "https://www.health.com/thmb/aQ1YqX8QJ3RYVPjZRMJZBLbx0MU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/OliveOil-ea74e49fad5640da8c3f330d5ee132ef.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "35%"
  },
  {
    "id": 25,
    "arabic_name": "زيت ذرة",
    "english_name": "Corn Oil",
    "amount": 44,
    "price": 75,
    "catId": "6",
    "image_url": "https://images.ctfassets.net/3s5io6mnxfqz/2VaqZY9ltrObyzotWcVeEa/497f15a68403cba6d1fa51d6c8a65148/AdobeStock_88586221.jpeg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "29%"
  },
  {
    "id": 26,
    "arabic_name": "زيت ذرة",
    "english_name": "Corn Oil",
    "amount": 44,
    "price": 75,
    "catId": "6",
    "image_url": "https://images.ctfassets.net/3s5io6mnxfqz/2VaqZY9ltrObyzotWcVeEa/497f15a68403cba6d1fa51d6c8a65148/AdobeStock_88586221.jpeg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "29%"
  },
  {
    "id": 27,
    "arabic_name": "زيت عباد الشمس",
    "english_name": "Sunflower Oil",
    "amount": 44,
    "price": 75,
    "catId": "6",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6A9XSQxSF7jjCx9PZk2YfKN6NmZ-VrK4erA&s",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "29%"
  },
  {
    "id": 28,
    "arabic_name": "زبدة لورباك",
    "english_name": "Lurpak Butter",
    "amount": 5,
    "price": 66,
    "catId": "6",
    "image_url": "https://jggp.jayagrocer.com/cdn/shop/products/000120-1-1_83502a8e-17c0-43ed-bdbf-bfe141c9b15b_800x.jpg?v=1679299253",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "50%"
  },
  {
    "id": 29,
    "arabic_name": "زبدة كي دي دي",
    "english_name": "KDD Butter",
    "amount": 5,
    "price": 46,
    "catId": "6",
    "image_url": "https://cdn.taw9eel.com/media/catalog/product/cache/1/image/519x/9df78eab33525d08d6e5fb8d27136e95/k/k/kkdc036-en_1.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "40%"
  },
  {
    "id": 30,
    "arabic_name": "زبدة فيرن",
    "english_name": "President Butter",
    "amount": 5,
    "price": 46,
    "catId": "6",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfvFGs_4l5FD5mwZPmb850Vw1w8v9Ut0Ve0g&s",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "30%"
  },
  {
    "id": 31,
    "arabic_name": "زبدة المراعي",
    "english_name": "Almarai Butter",
    "amount": 5,
    "price": 46,
    "catId": "6",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV81-qmTtrhIM9jAhjel5yAlalIM4tkfXBrQ&s",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "35%"
  },
  {
    "id": 32,
    "arabic_name": "زيت السمسم",
    "english_name": "Sesame Oil",
    "amount": 6,
    "price": 85,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/61g1qtblYvL._AC_UF894,1000_QL80_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 33,
    "arabic_name": "زيت الكانولا",
    "english_name": "Canola Oil",
    "amount": 10,
    "price": 90,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/71Yd6Y9SejL.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 34,
    "arabic_name": "زيت النخيل",
    "english_name": "Palm Oil",
    "amount": 8,
    "price": 70,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/81yQNMEFT4L.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 35,
    "arabic_name": "زيت جوز الهند",
    "english_name": "Coconut Oil",
    "amount": 5,
    "price": 120,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/71amPvapbbL.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 36,
    "arabic_name": "زيت العنب",
    "english_name": "Grapeseed Oil",
    "amount": 7,
    "price": 95,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/41PoAA5-GIL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 37,
    "arabic_name": "زيت الفول السوداني",
    "english_name": "Peanut Oil",
    "amount": 6,
    "price": 80,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/41TrjrvSLIL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 38,
    "arabic_name": "زيت الخردل",
    "english_name": "Mustard Oil",
    "amount": 4,
    "price": 75,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/61y1Ffac8NL._AC_SX522_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "25%"
  },
  {
    "id": 39,
    "arabic_name": "زيت الترفاس",
    "english_name": "Truffle Oil",
    "amount": 3,
    "price": 150,
    "catId": "6",
    "image_url": "https://images-na.ssl-images-amazon.com/images/I/414U7dRieeL._AC_UL600_SR600,600_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "30%"
  },
  {
    "id": 40,
    "arabic_name": "زيت الزيتون البكر",
    "english_name": "Extra Virgin Olive Oil",
    "amount": 5,
    "price": 130,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/31ozX74w5TL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 41,
    "arabic_name": "زيت اللافندر",
    "english_name": "Lavender Oil",
    "amount": 3,
    "price": 60,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/41XqnxS2UYL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 42,
    "arabic_name": "زيت الجوز",
    "english_name": "Walnut Oil",
    "amount": 4,
    "price": 110,
    "catId": "6",
    "image_url": "https://m.media-amazon.com/images/I/61cwsPCgKOL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 43,
    "arabic_name": "بيبسي",
    "english_name": "Pepsi",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/51hiRv+wWgL._SY300_SX300_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 44,
    "arabic_name": "كوكاكولا",
    "english_name": "Coca-Cola",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/616T7IPCn8L._AC_UL320_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 45,
    "arabic_name": "سبرايت",
    "english_name": "Sprite",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/51PGB50OtiL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 46,
    "arabic_name": "ريدبول",
    "english_name": "Red Bul",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/61GLb4R5pqL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 47,
    "arabic_name": "صودا شوكولاته",
    "english_name": "Chocolate Soda",
    "amount": 20,
    "price": 10,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/416FuX+vtlL._AC_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 48,
    "arabic_name": "صودا برتقال",
    "english_name": "Orange Soda",
    "amount": 30,
    "price": 12,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71gBtXpVZ6L._SX522_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 49,
    "arabic_name": "صودا ليمون",
    "english_name": "Lemon Soda",
    "amount": 25,
    "price": 11,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/21YujQC+3-L._AC_UL320_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 50,
    "arabic_name": "صودا تفاح",
    "english_name": "Apple Soda",
    "amount": 15,
    "price": 13,
    "catId": "1",
    "image_url": "https://images-eu.ssl-images-amazon.com/images/I/61TEazg2PxL._AC_UL600_SR600,600_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 51,
    "arabic_name": "صودا عنب",
    "english_name": "Grape Soda",
    "amount": 18,
    "price": 14,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/41x+p8YcY1L._SY300_SX300_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "25%"
  },
  {
    "id": 52,
    "arabic_name": "صودا مانجو",
    "english_name": "Mango Soda",
    "amount": 22,
    "price": 15,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/61ebX0SSmpS._AC_UL320_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 53,
    "arabic_name": "صودا كولا",
    "english_name": "Cola Soda",
    "amount": 35,
    "price": 9,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71g2cpkaDkL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "5%"
  },
  {
    "id": 54,
    "arabic_name": "صودا فراولة",
    "english_name": "Strawberry Soda",
    "amount": 17,
    "price": 12,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/81HqY-nZxFL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 55,
    "arabic_name": "صودا كيوي",
    "english_name": "Kiwi Soda",
    "amount": 20,
    "price": 13,
    "catId": "1",
    "image_url": "https://images-eu.ssl-images-amazon.com/images/I/51NYq9qV0UL._AC_UL165_SR165,165_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 56,
    "arabic_name": "نسكافيه جولد",
    "english_name": "Nescafé Gold",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/61yPV2Bm-GL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 57,
    "arabic_name": "عصير جهينه",
    "english_name": "Juhayna Juice",
    "amount": 1500,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71z2MbsgKEL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 58,
    "arabic_name": "شاي ليبتون",
    "english_name": "Lipton Tea",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71InKkskNML._AC_UL320_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 59,
    "arabic_name": "مياه معدنيه صافي",
    "english_name": "Safi Mineral Water",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/51iXpEinlEL.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 60,
    "arabic_name": "فيمتو",
    "english_name": "Vimto",
    "amount": 0,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71FlhjFzN5L._AC_UL320_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 61,
    "arabic_name": "قهوة",
    "english_name": "Nescafe 3in1",
    "amount": 900,
    "price": 1200,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/81gows7eThL._AC_SX679_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 62,
    "arabic_name": "عصير التفاح",
    "english_name": "Apple Juice",
    "amount": 5000,
    "price": 900,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71jg0usvl1L._AC_UL320_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 63,
    "arabic_name": "مياه معدنية أكوافينا",
    "english_name": "Aquafina Mineral Water",
    "amount": 6000,
    "price": 400,
    "catId": "1",
    "image_url": "https://m.media-amazon.com/images/I/71yL7ai74yL._AC_SY741_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 64,
    "arabic_name": "رقائق البطاطس",
    "english_name": "Potato Chips",
    "amount": 0,
    "price": 400,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/718WD89sVFL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 65,
    "arabic_name": "شيبس ناتشوز",
    "english_name": "Nachos Chips",
    "amount": 10,
    "price": 20,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/61wC2CO2g7L.__AC_SY300_SX300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 66,
    "arabic_name": "بسكويت دايجستيف",
    "english_name": "Digestive Biscuits",
    "amount": 15,
    "price": 25,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/81YmaESXaHL._AC_UF1000,1000_QL80_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 67,
    "arabic_name": "بسكويت الشوفان",
    "english_name": "Oat Biscuits",
    "amount": 12,
    "price": 22,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/61z0n5rKu+L._AC_SX679_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 68,
    "arabic_name": "شيبس برينجلز",
    "english_name": "Pringles Chips",
    "amount": 8,
    "price": 30,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/71XHoqzGNcL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 69,
    "arabic_name": "فشار ناتشوز",
    "english_name": "Nachos Popcorn",
    "amount": 20,
    "price": 18,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/71NiXqDQvAL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 70,
    "arabic_name": "شيبس ليز",
    "english_name": "Lay's Chips",
    "amount": 15,
    "price": 28,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/61vs7ucqGKL._SX300_SY300_QL70_FMwebp_.jpgg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 71,
    "arabic_name": "تشيتوس",
    "english_name": "Cheetos",
    "amount": 10,
    "price": 25,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/81tR0LGDgbL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 72,
    "arabic_name": "بسكويت أوريو",
    "english_name": "Oreo Cookies",
    "amount": 12,
    "price": 32,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/413xd8lakSL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 73,
    "arabic_name": "فريتوس",
    "english_name": "Fritos",
    "amount": 8,
    "price": 27,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/71++gfCFKEL._AC_UL320_.jpgg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 74,
    "arabic_name": "شوكولاتة كيندر",
    "english_name": "Kinder Chocolate",
    "amount": 6,
    "price": 35,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/51cebMPapdL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 75,
    "arabic_name": "كاسات الذرة",
    "english_name": "Doritos",
    "amount": 10,
    "price": 28,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/71-ZeXNs9nL._AC_SX679_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 76,
    "arabic_name": "سنيكرز",
    "english_name": "Snickers",
    "amount": 6,
    "price": 33,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/61z0U+vQ8YL._AC_SR180,120_QL70_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "5%"
  },
  {
    "id": 77,
    "arabic_name": "كيك بوب",
    "english_name": "Cake Pops",
    "amount": 15,
    "price": 30,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/81Aw-l+q27L._AC_SY300_SX300_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 78,
    "arabic_name": "شوكولاتة كيندر",
    "english_name": "Kinder Chocolate",
    "amount": 10,
    "price": 32,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/61cO6qYFfkL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 79,
    "arabic_name": "بسكويت الشوفان",
    "english_name": "Oat Biscuits",
    "amount": 6,
    "price": 22,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/61z0n5rKu+L._AC_SX300_SY300_.jpg",
    "boycott": true,
    "favorite": true,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 80,
    "arabic_name": "تشيبس برينجلز",
    "english_name": "Pringles Chips",
    "amount": 8,
    "price": 28,
    "catId": "2",
    "image_url": "https://m.media-amazon.com/images/I/71XHoqzGNcL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 81,
    "arabic_name": "داش",
    "english_name": "dash",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/61CdyA7HUJL._AC_SX569_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 82,
    "arabic_name": "داون",
    "english_name": "dawn",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/51F+vpGMEkL._AC_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 83,
    "arabic_name": "بينجو",
    "english_name": "bingo",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71Kq5pVKReL._AC_SY450_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 84,
    "arabic_name": "ديتول",
    "english_name": "dettol",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/61Tn7911gsL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 85,
    "arabic_name": "داوني",
    "english_name": "downy",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/713tLtcNfpL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 86,
    "arabic_name": "ايريل",
    "english_name": "ariel",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/61gteTDSVJL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 87,
    "arabic_name": "برف",
    "english_name": "bref",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71933mXvX5L._AC_SY879_PIbundle-3,TopRight,0,0_SH20_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 88,
    "arabic_name": "فيري",
    "english_name": "fairy",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/81uWe3SktAL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 89,
    "arabic_name": "كلاجون",
    "english_name": "calgon",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/81b4OHv0epL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 90,
    "arabic_name": "جين",
    "english_name": "gain",
    "amount": 1,
    "price": 46,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/81n9JiTYrSL._AC_UL320_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 91,
    "arabic_name": "صابون سائل",
    "english_name": "Liquid Soap",
    "amount": 3,
    "price": 28,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/61-s5UJQQyL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": 10
  },
  {
    "id": 92,
    "arabic_name": "مسحوق غسيل",
    "english_name": "Laundry Powder",
    "amount": 5,
    "price": 65,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71uH8Gs+-GL._AC_SY450_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 93,
    "arabic_name": "منظف الزجاج",
    "english_name": "Glass Cleaner",
    "amount": 2,
    "price": 33,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/61Avjk2n1PL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 94,
    "arabic_name": "مطهر أرضيات",
    "english_name": "Floor Disinfectant",
    "amount": 4,
    "price": 42,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71wijozPl9L.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 95,
    "arabic_name": "مبيض ملابس",
    "english_name": "Clothes Bleach",
    "amount": 3,
    "price": 54,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/51gxQSMO5pL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": 15
  },
  {
    "id": 96,
    "arabic_name": "منظف حمام",
    "english_name": "Toilet Cleaner",
    "amount": 6,
    "price": 39,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/51XQ+bG37rL._AC_SY879_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 97,
    "arabic_name": "منظف مطبخ",
    "english_name": "Kitchen Cleaner",
    "amount": 1,
    "price": 47,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71dqxCguxbL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": 5
  },
  {
    "id": 98,
    "arabic_name": "مزيل البقع",
    "english_name": "Stain Remover",
    "amount": 4,
    "price": 63,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/51gpP0nsDUL._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 99,
    "arabic_name": "منظف متعدد الاستخدامات",
    "english_name": "All-Purpose Cleaner",
    "amount": 2,
    "price": 58,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71bKOVgTdjL._AC._SR360,460.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": 20
  },
  {
    "id": 100,
    "arabic_name": "معطر جو",
    "english_name": "Air Freshener",
    "amount": 5,
    "price": 23,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/81steG2xI5L._AC_UL320_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 101,
    "arabic_name": "منظف سجاد",
    "english_name": "Carpet Cleaner",
    "amount": 7,
    "price": 67,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/617PuVzPZML._AC_UL320_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 102,
    "arabic_name": "منظف أثاث",
    "english_name": "Furniture Polish",
    "amount": 1,
    "price": 69,
    "catId": "3",
    "image_url": "https://m.media-amazon.com/images/I/71Y0vxxlKML.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": 12
  },
  {
    "id": 103,
    "arabic_name": "دجاج مجمد",
    "english_name": "Frozen Chicken",
    "amount": 20,
    "price": 120,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/6149kd0kV9L._AC_SX569_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 104,
    "arabic_name": "سمك فيليه مجمد",
    "english_name": "Frozen Fish Fillet",
    "amount": 15,
    "price": 150,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/61GVG1q-2vL._AC_UF894,1000_QL80_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 105,
    "arabic_name": "بطاطس مجمدة",
    "english_name": "Frozen Potatoes",
    "amount": 30,
    "price": 80,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/71KG5psdXxL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 106,
    "arabic_name": "خضروات مجمدة",
    "english_name": "Frozen Vegetables",
    "amount": 25,
    "price": 100,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/51tKcXQ47FL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 107,
    "arabic_name": "لحم بقري مجمد",
    "english_name": "Frozen Beef",
    "amount": 10,
    "price": 200,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/610r+Mkd5TL._AC_SY300_SX300_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": true,
    "sale %": "5%"
  },
  {
    "id": 108,
    "arabic_name": "دجاج مكعبات مجمد",
    "english_name": "Frozen Chicken Cubes",
    "amount": 18,
    "price": 130,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/51kHWz+jhOL.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "12%"
  },
  {
    "id": 109,
    "arabic_name": "سمك مجمد",
    "english_name": "Frozen Fish",
    "amount": 20,
    "price": 140,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/91M3LBkvsXL.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 110,
    "arabic_name": "فطائر مجمدة",
    "english_name": "Frozen Pastries",
    "amount": 12,
    "price": 90,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/41Ldzgnq+gL._SY300_SX300_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 111,
    "arabic_name": "دجاج مشوي مجمد",
    "english_name": "Frozen Grilled Chicken",
    "amount": 8,
    "price": 160,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/51ULJPfZpDL._SX300_SY300_QL70_FMwebp_.jpg",
    "boycott": false,
    "favorite": true,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 112,
    "arabic_name": "برجر مجمد",
    "english_name": "Frozen Burger",
    "amount": 15,
    "price": 120,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/61p1YUNxbuL._SY606_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 113,
    "arabic_name": "نقانق مجمدة",
    "english_name": "Frozen Sausages",
    "amount": 20,
    "price": 100,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/71ppfvYMHML._SX522_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 114,
    "arabic_name": "سبانخ مجمدة",
    "english_name": "Frozen Spinach",
    "amount": 12,
    "price": 90,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/81hoplNJWlL._AC_UF1000,1000_QL80_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 115,
    "arabic_name": "فواكه مجمدة",
    "english_name": "Frozen Fruits",
    "amount": 25,
    "price": 110,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/41-4qkl+Y6L._SY300_SX300_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "10%"
  },
  {
    "id": 116,
    "arabic_name": "لحم دجاج مجمد",
    "english_name": "Frozen Chicken Meat",
    "amount": 18,
    "price": 130,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/81nzbRm80vL._AC_SX679_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": false,
    "sale %": null
  },
  {
    "id": 117,
    "arabic_name": "جزر مجمد",
    "english_name": "Frozen Carrots",
    "amount": 22,
    "price": 70,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/813s3w7BS9L._AC_UF1000,1000_QL80_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "5%"
  },
  {
    "id": 118,
    "arabic_name": "آيس كريم مجمد",
    "english_name": "Frozen Ice Cream",
    "amount": 10,
    "price": 50,
    "catId": "7",
    "image_url": "https://m.media-amazon.com/images/I/71AKsxVVrDL.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 119,
    "arabic_name": "صوص الطماطم",
    "english_name": "Ketchup",
    "amount": 5,
    "price": 30,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/81J8EHMGjYL.jpgeinz.com/images/Heinz-Ketchup.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "35%"
  },
  {
    "id": 120,
    "arabic_name": "صوص حار",
    "english_name": "Hot Sauce",
    "amount": 5,
    "price": 25,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51BY5G4tjgL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "30%"
  },
  {
    "id": 121,
    "arabic_name": "صوص الصويا",
    "english_name": "Soy Sauce",
    "amount": 5,
    "price": 20,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/61N58xgMiML.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "25%"
  },
  {
    "id": 122,
    "arabic_name": "صوص الباربكيو",
    "english_name": "Barbecue Sauce",
    "amount": 5,
    "price": 40,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51KpD3elfML.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 123,
    "arabic_name": "صوص الثوم",
    "english_name": "Garlic Sauce",
    "amount": 5,
    "price": 35,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/81nYbLra9NL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 124,
    "arabic_name": "صوص الطحينة",
    "english_name": "Tahini Sauce",
    "amount": 5,
    "price": 25,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/61IG+ALpTUL._AC_SY300_SX300_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "30%"
  },
  {
    "id": 125,
    "arabic_name": "صوص الخردل",
    "english_name": "Mustard Sauce",
    "amount": 5,
    "price": 20,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51B7G9-vkWL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "25%"
  },
  {
    "id": 126,
    "arabic_name": "صوص البيستو",
    "english_name": "Pesto Sauce",
    "amount": 5,
    "price": 50,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/71x8DxzDqLL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": false,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 127,
    "arabic_name": "صوص الطماطم",
    "english_name": "Ketchup",
    "amount": 5,
    "price": 30,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51ZZd2JTAIL._AC_UF894,1000_QL80_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "35%"
  },
  {
    "id": 128,
    "arabic_name": "صوص حار",
    "english_name": "Hot Sauce",
    "amount": 5,
    "price": 25,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51c7YdlR8zL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "30%"
  },
  {
    "id": 129,
    "arabic_name": "صوص الصويا",
    "english_name": "Soy Sauce",
    "amount": 5,
    "price": 20,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51rojjwaG7L.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "25%"
  },
  {
    "id": 130,
    "arabic_name": "صوص الباربكيو",
    "english_name": "Barbecue Sauce",
    "amount": 5,
    "price": 40,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/51oE3Qh1jxL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 131,
    "arabic_name": "صوص الثوم",
    "english_name": "Garlic Sauce",
    "amount": 5,
    "price": 35,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/71M-mF1nOOL.__AC_SX300_SY300_QL70_ML2_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  },
  {
    "id": 132,
    "arabic_name": "صوص الخردل",
    "english_name": "Mustard Sauce",
    "amount": 5,
    "price": 20,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/71mIVuLphzL._AC_UF894,1000_QL80_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "25%"
  },
  {
    "id": 133,
    "arabic_name": "صوص الفلفل",
    "english_name": "Pepper Sauce",
    "amount": 5,
    "price": 30,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/71OfghemM8L.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "20%"
  },
  {
    "id": 134,
    "arabic_name": "صوص البيستو",
    "english_name": "Pesto Sauce",
    "amount": 5,
    "price": 50,
    "catId": "8",
    "image_url": "https://m.media-amazon.com/images/I/71S+Fa1dZ4L._AC_SY300_SX300_.jpg",
    "boycott": true,
    "favorite": false,
    "isSale": true,
    "sale %": "15%"
  }
]
let newData = {}
Products.forEach(item => {
  newData[item.id] = {
    arabic_name: item.arabic_name,
    english_name: item.english_name,
    amount: item.amount,
    catId: item.amount,
    image_url: item.image_url,
    boycott: item.boycott,
    favorite: item.favorite,
    isSale: item.isSale,
    "sale %": item['sale %'] || null,
  }
})

const jsonData = JSON.stringify(newData, null, 2);
fs.writeFileSync('allProducts.json', jsonData, 'utf8');

const app = express();
app.use(bodyParser.json());
app.use(cors());

app.post('/create-checkout-session', async (req, res) => {
  try {
    const { cartArray, userName, userEmail } = req.body;

    // Create a new Stripe Checkout session
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: cartArray.map(product => ({
        price_data: {
          currency: 'egp',
          product_data: {
            name: product.english_name
          },
          unit_amount: product.price  // Price in cents
        },
        quantity: 1
      })),
      mode: 'payment',
      success_url: 'http://localhost:8080/success',
      cancel_url: 'http://localhost:8080/cancel',
      customer_email: userEmail, // Pass customer's email to pre-fill email field
      metadata: {
        customer_name: userName // Store customer's name as metadata
      }
    });

    // Send the session ID to the frontend
    res.json({ id: session.id });
  } catch (error) {
    console.error('Error creating checkout session:', error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});

app.listen(3001, () => {
  console.log('Server running on port 3001');
});
